/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Crazymaverickdc (https://sketchfab.com/Crazymaverickdc)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/naples-archeological-museum-athena-villa-ma-ec7f919e9e3b4982bf32697923eb3fc0
Title: Naples - Archeological Museum - Athena Villa Ma…
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import athena from "../assets/3d/athena.glb"
import { useFrame, useThree } from "@react-three/fiber";


export function Athena({isRotating,setIsRotating,...props}) {

  const { nodes, materials } = useGLTF(athena);
  const athenaRef = useRef();

  const {gl,viewport} = useThree();

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
 const dampingFactor = 0.95;

 useFrame(() => {
    if (isRotating) {
      athenaRef.current.rotation.y += 0.01;
    }
    
});
const isDragging = useRef(false);

useEffect(() => {
    const handlePointerDown = () => {
      isDragging.current = true;
      setIsRotating(false);
    };

    const handlePointerUp = () => {
      isDragging.current = false;
      setIsRotating(true);
    };

    gl.domElement.addEventListener('pointerdown', handlePointerDown);
    gl.domElement.addEventListener('pointerup', handlePointerUp);

    return () => {
      gl.domElement.removeEventListener('pointerdown', handlePointerDown);
      gl.domElement.removeEventListener('pointerup', handlePointerUp);
    };
  }, [gl.domElement]);

  return (
    <group {...props} dispose={null} ref={athenaRef}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.main}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.main}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.main}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/naples_-_archeological_museum_-_athena_villa_ma..glb");
