/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SMK – National Gallery of Denmark (https://sketchfab.com/smkmuseum)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/discobolus-the-discus-thrower-50f50abf45414ad8a658325df7a5fcb3
Title: Discobolus (The Discus Thrower)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import discobolus from "../assets/3d/discobolus_the_discus_thrower.glb"
import { useFrame, useThree } from "@react-three/fiber";

export function Discobolus({isRotating,setIsRotating,...props}) {

  const { nodes, materials } = useGLTF(discobolus);

  const discobolusRef = useRef();

  const {gl,viewport} = useThree();

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
 const dampingFactor = 0.95;

 useFrame(() => {
    if (isRotating) {
        discobolusRef.current.rotation.y += 0.01;
    }
    
});
const isDragging = useRef(false);

useEffect(() => {
    const handlePointerDown = () => {
      isDragging.current = true;
      setIsRotating(false);
    };

    const handlePointerUp = () => {
      isDragging.current = false;
      setIsRotating(true);
    };

    gl.domElement.addEventListener('pointerdown', handlePointerDown);
    gl.domElement.addEventListener('pointerup', handlePointerUp);

    return () => {
      gl.domElement.removeEventListener('pointerdown', handlePointerDown);
      gl.domElement.removeEventListener('pointerup', handlePointerUp);
    };
  }, [gl.domElement]);


  
  return (
    <group {...props} dispose={null} ref={discobolusRef}>
      <group rotation={[-Math.PI / 2, 0, -1]} >
        <group position={[-0, -2.47, -0.281]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials["default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials["default"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/discobolus_the_discus_thrower.glb");
